### ISSUE TITLE
sections overlapping in customizer.

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/Illyria#7]
Options for customizing the theme are overlapped in the customizer. Please see screenshots to get better idea http://prntscr.com/faofkd http://prntscr.com/faofug http://prntscr.com/faog70

**Comment by poonam279** [comment]
@rodica-andronache Same issue with the lawyeria-lite theme, http://prntscr.com/fgkavz http://prntscr.com/fgkb4t

**Comment by rodica-andronache** [comment]
this problems are from the parent theme
